#!/bin/sh
# Launches ssh client, connecting to the specified bandit level

if [ $# -ne 1 ] ; then
	echo "Usage: bandit <level_number>"
else
	case $1 in
		'-l') getpass -l
		;;
		*) pass=$(getpass $1)
		sshpass -p$pass ssh -o StrictHostKeyChecking=no bandit$1@bandit.labs.overthewire.org -p 2220
		;;
	esac
fi
