#!/bin/sh

T_PATH="$HOME/.config/termite"
C_FILE="$T_PATH/config"
F_ARR=($(ls $T_PATH))
input=-1
input_str=''
choices_str=''

if [ "$#" -ne 0 ]; then
	echo "Usage: conftheme"
	exit 1
fi


# Remove config from the list of options
for target in ${F_ARR[@]}; do
	if [ $target != "config" ] || [ $target != " " ]; then
		choices_str="$choices_str$target"
	fi
	if [ $target != ${F_ARR[-1]} ]; then
		choices_str="$choices_str\n"
	fi
done;

input_str=$(echo -e $choices_str | dmenu)

if [ ! $input_str ]; then
	echo "termetheme: error none selected"
	exit 1
fi

vim $T_PATH/$input_str
