#!/bin/sh

F_ARR=($(ls $T_PATH))
input_str=''
choices_str='i3\nnewsboat\npicom\vim\zsh'
ZSH_PATH="$HOME/.zshrc"
VIM_PATH="$HOME/.vimrc"
chosen_path=''

if [ "$#" -ne 0 ]; then
	input_str=$1
fi

case $input_str in
	zsh) chosen_path=$ZSH_PATH
	;;
	vim) chosen_path=$VIM_PATH
	;;
	*) chosen_path=''
esac

if [ ! $chosen_path ]; then
	echo "Unable to find $input_str configuration file"
	exit 1
fi

vim $chosen_path 
